### ISSUE TITLE
spanName isn't used

### ISSUE THREAD

**Issue by agilob** [simskij/xk6-distributed-tracing#29]
Is this intentional?

https://github.com/grafana/xk6-distributed-tracing/blob/72eb374947a2ef5291457d86d00eb689d9a23fa4/client/client.go#L83

I'm having a problem where traces sent by version `72eb374947a2ef5291457d86d00eb689d9a23fa4`  latest commit, aren't picked up by our services, instead a gateway service generates own trace_id which is carried over to other backends. I started reviewing code and notice the spanName isn't used, but passed with values like `HTTP OPTIONS`. Should users be able to configure it in Http constructor?

**Comment by Blinkuu** [comment]
Archiving this repository, as [k6/experimental/tracing](https://grafana.com/docs/k6/latest/javascript-api/k6-experimental/tracing/) module is now available in k6 OSS.
