### ISSUE TITLE
http headers are canonicalized before sending

### ISSUE THREAD

**Issue by agilob** [simskij/xk6-distributed-tracing#30]
Despite the header being specified in lower case https://github.com/grafana/xk6-distributed-tracing/blob/master/client/traceid.go#L16

when it's put to a map golang changes the key to a canonicalized version which always starts with [Uppercase letter](https://stackoverflow.com/questions/26351716/how-to-keep-key-case-sensitive-in-request-header-using-golang) this breaks compatibility of the b3 spec. Request aren't picked up by existing b3-compatible backends. 

The expected header is  `b3`, but remote backend receives `B3`, span and parent trace id aren't picked up:

![image](https://user-images.githubusercontent.com/2544251/213718178-ccddc260-e573-4930-b332-bdc9a57d9c11.png)

**Comment by Blinkuu** [comment]
Archiving this repository, as [k6/experimental/tracing](https://grafana.com/docs/k6/latest/javascript-api/k6-experimental/tracing/) module is now available in k6 OSS.
